sudo: true

language: python
python:
  - "2.7"


install:

  - pip install coveralls
  - pip install -r requirements.txt

# command to run tests
script: nosetests --with-coverage --cover-package=app

after_success:
  - coveralls

notifications:
  slack:
    on_success: never
    on_failure: never
  email: false




