"""empty message

Revision ID: 0ba949cd7336
Revises: d019819906bd
Create Date: 2018-05-23 22:07:37.967354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba949cd7336'
down_revision = 'd019819906bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.add_column('users', sa.Column('logged_in', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'logged_in')
    op.create_table('tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('token_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['token_user_id'], ['users.id'], name='tokens_token_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    )
    # ### end Alembic commands ###
