"""empty message

Revision ID: 49ad5cf8b780
Revises: 161dd502f86c
Create Date: 2018-05-17 21:09:49.536704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ad5cf8b780'
down_revision = '161dd502f86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_confirmed')
    # ### end Alembic commands ###
