"""empty message

Revision ID: 6fe8a3ce2f25
Revises: acef8e446154
Create Date: 2018-03-20 22:04:10.218507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe8a3ce2f25'
down_revision = 'acef8e446154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_password', sa.String(length=250), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('users', 'first_password')
    # ### end Alembic commands ###
